import type { ConfigGeneratorTemplateSchemaJson } from "./config-generator.types.js";

export const CONFIG_GENERATOR_REASONS = {
  writeBlocked: "CONFIG_WRITE_ENABLED=false. MVP permite apenas geração e preview.",
};

export const CONFIG_GENERATOR_GLOBAL_OBJECTS = [
  "RFC5735",
  "WORLD",
  "DEFAULT",
  "INTERNET",
  "BGP_BASELINE",
  "COMMUNITY_BASELINE",
] as const;

export const CONFIG_GENERATOR_TEMPLATES = [
  {
    name: "Huawei VRP - BGP Cliente com Community",
    serviceType: "bgp_customer_community",
    vendor: "huawei",
    platform: "vrp",
    templateKey: "huawei_vrp_bgp_customer_community",
    renderer: "huawei_vrp_bgp_customer_community_v1",
    version: "1.0.0",
    content: [
      "{{global_dependencies}}",
      "",
      "{{circuit_dependencies}}",
      "",
      "{{route_policy_import}}",
      "",
      "{{route_policy_export}}",
      "",
      "{{peer_binding}}",
      "",
      "{{postcheck}}",
      "",
      "{{rollback_placeholder}}",
    ].join("\n"),
    schemaJson: {
      fields: [
        { key: "circuitId", label: "Circuit ID", type: "string", required: true, placeholder: "1234" },
        { key: "customerName", label: "Customer Name", type: "string", required: true, placeholder: "CLIENTE_X" },
        { key: "localAsn", label: "ASN Local", type: "number", required: true, placeholder: "273309" },
        { key: "remoteAsn", label: "ASN Remoto", type: "number", required: true, placeholder: "65001" },
        { key: "interface", label: "Interface", type: "string", required: true, placeholder: "Eth-Trunk1.1234" },
        { key: "vlan", label: "VLAN", type: "number", required: true, placeholder: "1234" },
        { key: "subinterfaceId", label: "Subinterface ID", type: "number", placeholder: "1234" },
        { key: "allocationRangeKey", label: "Allocation Range Key", type: "string", placeholder: "l3vpn" },
        { key: "allocationReason", label: "Allocation Reason", type: "string", placeholder: "Sugerido pelo alocador" },
        { key: "importPolicyName", label: "Import Policy", type: "string", placeholder: "C1234_IMPORT" },
        { key: "exportPolicyName", label: "Export Policy", type: "string", placeholder: "C1234_EXPORT" },
        { key: "communityBase", label: "Community Base", type: "string", placeholder: "273309:1234" },
        { key: "prependProfile", label: "Prepend Profile", type: "string", placeholder: "P1" },
        { key: "peerLocalIpv4", label: "Peer IPv4 Local", type: "ipv4", required: true, placeholder: "10.0.0.1" },
        { key: "peerRemoteIpv4", label: "Peer IPv4 Remoto", type: "ipv4", required: true, placeholder: "10.0.0.2" },
        { key: "peerLocalIpv6", label: "Peer IPv6 Local", type: "ipv6", placeholder: "2001:db8::1" },
        { key: "peerRemoteIpv6", label: "Peer IPv6 Remoto", type: "ipv6", placeholder: "2001:db8::2" },
        { key: "ipv4Prefixes", label: "Prefixos IPv4", type: "array", required: true, placeholder: "203.0.113.0/24" },
        { key: "ipv6Prefixes", label: "Prefixos IPv6", type: "array", placeholder: "2001:db8:100::/48" },
        { key: "md5Secret", label: "MD5 Secret", type: "secret", placeholder: "optional" },
      ],
      blocks: [
        { key: "global_dependencies", title: "Dependências globais", classification: "global", statusHint: "existing" },
        { key: "circuit_dependencies", title: "Dependências do circuito", classification: "circuit", statusHint: "new" },
        { key: "route_policy_import", title: "Route-policy import", classification: "circuit", statusHint: "new" },
        { key: "route_policy_export", title: "Route-policy export", classification: "circuit", statusHint: "new" },
        { key: "peer_binding", title: "Peer binding", classification: "circuit", statusHint: "suggested" },
        { key: "postcheck", title: "Postcheck", classification: "circuit", statusHint: "manual" },
        { key: "rollback_placeholder", title: "Rollback placeholder", classification: "circuit", statusHint: "manual" },
      ],
    } satisfies ConfigGeneratorTemplateSchemaJson,
  },
  {
    name: "Huawei VRP - L2VPN VLAN",
    serviceType: "l2vpn_vlan",
    vendor: "huawei",
    platform: "vrp",
    templateKey: "huawei_vrp_l2vpn_vlan",
    renderer: "huawei_vrp_l2vpn_vlan_v1",
    version: "1.0.0",
    content: [
      "{{global_dependencies}}",
      "",
      "{{circuit_dependencies}}",
      "",
      "{{route_policy_import}}",
      "",
      "{{route_policy_export}}",
      "",
      "{{peer_binding}}",
      "",
      "{{postcheck}}",
      "",
      "{{rollback_placeholder}}",
    ].join("\n"),
    schemaJson: {
      fields: [
        { key: "circuitId", label: "Circuit ID", type: "string", required: true, placeholder: "1234" },
        { key: "customerName", label: "Customer Name", type: "string", required: true, placeholder: "CLIENTE_X" },
        { key: "deviceName", label: "Device Name", type: "string", placeholder: "PE-01" },
        { key: "interface", label: "Interface", type: "string", required: true, placeholder: "Eth-Trunk1.1234" },
        { key: "vlan", label: "VLAN", type: "number", required: true, placeholder: "1234" },
        { key: "subinterfaceId", label: "Subinterface ID", type: "number", placeholder: "601" },
        { key: "l2vcId", label: "L2VC ID", type: "number", placeholder: "601" },
        { key: "vsiId", label: "VSI ID", type: "number", placeholder: "601" },
        { key: "allocationScope", label: "Allocation Scope", type: "string", placeholder: "tenant" },
        { key: "allocationRangeKey", label: "Allocation Range Key", type: "string", placeholder: "l2vpn" },
        { key: "allocationReason", label: "Allocation Reason", type: "string", placeholder: "Sugerido pelo alocador" },
        { key: "interfacePortNumber", label: "Interface Port Number", type: "number", placeholder: "1" },
        { key: "untaggedRequired", label: "Untagged Required", type: "boolean", placeholder: "false" },
        { key: "mode", label: "Mode", type: "select", placeholder: "tagged", options: ["tagged", "untagged", "qinq"] },
        { key: "description", label: "Description", type: "string", placeholder: "L2VPN access" },
        { key: "mtu", label: "MTU", type: "number", placeholder: "1500" },
        { key: "serviceType", label: "Service Type", type: "string", placeholder: "l2vpn_vlan" },
        { key: "neighborSite", label: "Neighbor Site", type: "string", placeholder: "SITE-B" },
        { key: "endpointRole", label: "Endpoint Role", type: "string", placeholder: "access" },
        { key: "peerLocalIpv4", label: "Peer IPv4 Local", type: "ipv4", placeholder: "10.0.0.1" },
        { key: "peerRemoteIpv4", label: "Peer IPv4 Remoto", type: "ipv4", placeholder: "10.0.0.2" },
        { key: "ipv4Prefixes", label: "Prefixos IPv4", type: "array", placeholder: "203.0.113.0/24" },
        { key: "md5Secret", label: "MD5 Secret", type: "secret", placeholder: "optional" },
      ],
      blocks: [
        { key: "global_dependencies", title: "Dependências globais", classification: "global", statusHint: "existing" },
        { key: "circuit_dependencies", title: "Dependências do circuito", classification: "circuit", statusHint: "new" },
        { key: "route_policy_import", title: "Route-policy import", classification: "circuit", statusHint: "manual" },
        { key: "route_policy_export", title: "Route-policy export", classification: "circuit", statusHint: "manual" },
        { key: "peer_binding", title: "Peer binding", classification: "circuit", statusHint: "suggested" },
        { key: "postcheck", title: "Postcheck", classification: "circuit", statusHint: "manual" },
        { key: "rollback_placeholder", title: "Rollback placeholder", classification: "circuit", statusHint: "manual" },
      ],
    } satisfies ConfigGeneratorTemplateSchemaJson,
  },
  {
    name: "Huawei VRP - L2VPN PTP/L2VC",
    serviceType: "l2vpn_ptp",
    vendor: "huawei",
    platform: "vrp",
    templateKey: "huawei_vrp_l2vpn_ptp_l2vc",
    renderer: "huawei_vrp_l2vpn_ptp_l2vc_v1",
    version: "1.0.0",
    content: [
      "{{global_dependencies}}",
      "",
      "{{circuit_dependencies}}",
      "",
      "{{interface_binding}}",
      "",
      "{{l2vc_binding}}",
      "",
      "{{peer_binding}}",
      "",
      "{{postcheck}}",
      "",
      "{{rollback_placeholder}}",
    ].join("\n"),
    schemaJson: {
      fields: [
        { key: "circuitId", label: "Circuit ID", type: "string", required: true, placeholder: "601" },
        { key: "customerName", label: "Customer Name", type: "string", required: true, placeholder: "CLIENTE_X" },
        { key: "localDeviceName", label: "Local Device", type: "string", placeholder: "PE-01" },
        { key: "localInterface", label: "Local Interface", type: "string", required: true, placeholder: "Eth-Trunk1" },
        { key: "interface", label: "Subinterface", type: "string", required: true, placeholder: "Eth-Trunk1.601" },
        { key: "vlan", label: "VLAN", type: "number", required: true, placeholder: "601" },
        { key: "subinterfaceId", label: "Subinterface ID", type: "number", placeholder: "601" },
        { key: "l2vcId", label: "L2VC ID", type: "number", required: true, placeholder: "601" },
        { key: "remotePeerIp", label: "Remote Peer IP", type: "ipv4", required: true, placeholder: "10.1.1.2" },
        { key: "remoteSite", label: "Remote Site", type: "string", placeholder: "SITE-B" },
        { key: "remoteDeviceName", label: "Remote Device", type: "string", placeholder: "PE-02" },
        { key: "encapsulation", label: "Encapsulation", type: "select", placeholder: "dot1q", options: ["dot1q", "qinq", "untagged"] },
        { key: "description", label: "Description", type: "string", placeholder: "L2VC access" },
        { key: "mtu", label: "MTU", type: "number", placeholder: "1500" },
        { key: "controlWord", label: "Control Word", type: "boolean", placeholder: "false" },
        { key: "tunnelPolicy", label: "Tunnel Policy", type: "string", placeholder: "TP_L2VPN" },
        { key: "allocationScope", label: "Allocation Scope", type: "string", placeholder: "tenant" },
        { key: "allocationRangeKey", label: "Allocation Range Key", type: "string", placeholder: "l2vpn" },
        { key: "allocationReason", label: "Allocation Reason", type: "string", placeholder: "Sugerido pelo alocador" },
        { key: "serviceType", label: "Service Type", type: "string", placeholder: "l2vpn_ptp" },
        { key: "endpointRole", label: "Endpoint Role", type: "string", placeholder: "access" },
        { key: "neighborSite", label: "Neighbor Site", type: "string", placeholder: "SITE-B" },
      ],
      blocks: [
        { key: "global_dependencies", title: "Dependências globais", classification: "global", statusHint: "existing" },
        { key: "circuit_dependencies", title: "Dependências do circuito", classification: "circuit", statusHint: "new" },
        { key: "interface_binding", title: "Interface binding", classification: "circuit", statusHint: "new" },
        { key: "l2vc_binding", title: "L2VC binding", classification: "circuit", statusHint: "new" },
        { key: "peer_binding", title: "Peer binding", classification: "circuit", statusHint: "suggested" },
        { key: "postcheck", title: "Postcheck", classification: "circuit", statusHint: "manual" },
        { key: "rollback_placeholder", title: "Rollback placeholder", classification: "circuit", statusHint: "manual" },
      ],
    } satisfies ConfigGeneratorTemplateSchemaJson,
  },
  {
    name: "Huawei VRP - L2VPN PTMP/VSI",
    serviceType: "l2vpn_ptmp",
    vendor: "huawei",
    platform: "vrp",
    templateKey: "huawei_vrp_l2vpn_ptmp_vsi",
    renderer: "huawei_vrp_l2vpn_ptmp_vsi_v1",
    version: "1.0.0",
    content: [
      "{{global_dependencies}}",
      "",
      "{{circuit_dependencies}}",
      "",
      "{{vsi_definition}}",
      "",
      "{{peer_binding}}",
      "",
      "{{access_binding}}",
      "",
      "{{postcheck}}",
      "",
      "{{rollback_placeholder}}",
    ].join("\n"),
    schemaJson: {
      fields: [
        { key: "circuitId", label: "Circuit ID", type: "string", required: true, placeholder: "602" },
        { key: "customerName", label: "Customer Name", type: "string", required: true, placeholder: "CLIENTE_X" },
        { key: "vsiName", label: "VSI Name", type: "string", required: true, placeholder: "VSI_CLIENTE_X" },
        { key: "vsiId", label: "VSI ID", type: "number", required: true, placeholder: "602" },
        { key: "vlan", label: "VLAN", type: "number", required: true, placeholder: "602" },
        { key: "subinterfaceId", label: "Subinterface ID", type: "number", placeholder: "602" },
        { key: "accessInterface", label: "Access Interface", type: "string", required: true, placeholder: "Eth-Trunk1.602" },
        { key: "interface", label: "Interface (alias)", type: "string", placeholder: "Eth-Trunk1.602" },
        { key: "remotePeers", label: "Remote Peers", type: "array", required: true, placeholder: "10.1.1.2" },
        { key: "siteRole", label: "Site Role", type: "string", placeholder: "hub" },
        { key: "neighborSites", label: "Neighbor Sites", type: "array", placeholder: "SITE-B" },
        { key: "description", label: "Description", type: "string", placeholder: "VSI multipoint" },
        { key: "mtu", label: "MTU", type: "number", placeholder: "1500" },
        { key: "encapsulation", label: "Encapsulation", type: "select", placeholder: "dot1q", options: ["dot1q", "qinq", "untagged"] },
        { key: "allocationScope", label: "Allocation Scope", type: "string", placeholder: "tenant" },
        { key: "allocationRangeKey", label: "Allocation Range Key", type: "string", placeholder: "l2vpn" },
        { key: "allocationReason", label: "Allocation Reason", type: "string", placeholder: "Sugerido pelo alocador" },
        { key: "serviceType", label: "Service Type", type: "string", placeholder: "l2vpn_ptmp" },
        { key: "endpointRole", label: "Endpoint Role", type: "string", placeholder: "access" },
        { key: "neighborSite", label: "Neighbor Site", type: "string", placeholder: "SITE-B" },
      ],
      blocks: [
        { key: "global_dependencies", title: "Dependências globais", classification: "global", statusHint: "existing" },
        { key: "circuit_dependencies", title: "Dependências do circuito", classification: "circuit", statusHint: "new" },
        { key: "vsi_definition", title: "VSI definition", classification: "circuit", statusHint: "new" },
        { key: "peer_binding", title: "Peer binding", classification: "circuit", statusHint: "suggested" },
        { key: "access_binding", title: "Access binding", classification: "circuit", statusHint: "new" },
        { key: "postcheck", title: "Postcheck", classification: "circuit", statusHint: "manual" },
        { key: "rollback_placeholder", title: "Rollback placeholder", classification: "circuit", statusHint: "manual" },
      ],
    } satisfies ConfigGeneratorTemplateSchemaJson,
  },
] as const;

export const L2VPN_PTP_TEMPLATE_KEY = "huawei_vrp_l2vpn_ptp_l2vc";
export const L2VPN_PTMP_TEMPLATE_KEY = "huawei_vrp_l2vpn_ptmp_vsi";
export const L2VPN_PTP_SERVICE_TYPES = new Set(["l2vpn_ptp", "vpws", "l2vc"]);
export const L2VPN_PTMP_SERVICE_TYPES = new Set(["l2vpn_ptmp", "vpls", "vsi"]);
export const L2VPN_SERVICE_TYPES = new Set([...L2VPN_PTP_SERVICE_TYPES, ...L2VPN_PTMP_SERVICE_TYPES, "l2vpn_vlan", "l2vpn"]);

export type ConfigGeneratorSeedTemplate = (typeof CONFIG_GENERATOR_TEMPLATES)[number];
