import { desc, eq, inArray } from "drizzle-orm";
import { configTemplatesTable, db, devicesTable, provisioningJobsTable, provisioningStepsTable, reportsTable } from "@workspace/db";
import { auditLogsTable } from "@workspace/db";

function parseJson(value: string | null): unknown {
  if (!value) return null;
  try {
    return JSON.parse(value);
  } catch {
    return null;
  }
}

function renderTemplate(template: string, params: Record<string, unknown>): string {
  let rendered = template;
  for (const [key, value] of Object.entries(params)) {
    const replacement = String(value ?? "");
    rendered = rendered.replaceAll(`{{${key}}}`, replacement);
    rendered = rendered.replaceAll(`{{ ${key} }}`, replacement);
  }
  return rendered;
}

export async function getProvisioningJobDetail(id: number) {
  const [job] = await db.select().from(provisioningJobsTable).where(eq(provisioningJobsTable.id, id));
  if (!job) return null;

  const steps = await db.select({
    id: provisioningStepsTable.id,
    jobId: provisioningStepsTable.jobId,
    deviceId: provisioningStepsTable.deviceId,
    deviceHostname: devicesTable.hostname,
    stepName: provisioningStepsTable.stepName,
    status: provisioningStepsTable.status,
    configApplied: provisioningStepsTable.configApplied,
    output: provisioningStepsTable.output,
    errorMessage: provisioningStepsTable.errorMessage,
    executedAt: provisioningStepsTable.executedAt,
  })
    .from(provisioningStepsTable)
    .leftJoin(devicesTable, eq(provisioningStepsTable.deviceId, devicesTable.id))
    .where(eq(provisioningStepsTable.jobId, id));

  return {
    ...job,
    deviceIds: JSON.parse(job.deviceIds ?? "[]"),
    validatedAt: job.validatedAt?.toISOString() ?? null,
    executedAt: job.executedAt?.toISOString() ?? null,
    completedAt: job.completedAt?.toISOString() ?? null,
    createdAt: job.createdAt.toISOString(),
    steps: steps.map((step) => ({
      ...step,
      executedAt: step.executedAt?.toISOString() ?? null,
    })),
  };
}

export async function getProvisioningJobSummary(id: number) {
  const detail = await getProvisioningJobDetail(id);
  if (!detail) return null;
  const [template] = detail.templateId
    ? await db.select().from(configTemplatesTable).where(eq(configTemplatesTable.id, detail.templateId))
    : [];
  const deviceIds: number[] = detail.deviceIds ?? [];
  const targetDevices = deviceIds.length > 0
    ? await db.select().from(devicesTable).where(inArray(devicesTable.id, deviceIds))
    : [];

  return {
    detail,
    template: template ?? null,
    targetDevices,
  };
}

export async function buildProvisioningJobReportMarkdown(id: number) {
  const summary = await getProvisioningJobSummary(id);
  if (!summary) return null;

  const { detail, template, targetDevices } = summary;
  const parameters = parseJson(detail.parameters) as Record<string, unknown> | null;
  const auditTrail = await db.select().from(auditLogsTable)
    .where(eq(auditLogsTable.objectType, "provisioning_job"))
    .orderBy(desc(auditLogsTable.createdAt))
    .limit(10);

  const previewConfig = template && parameters
    ? renderTemplate(template.template, parameters)
    : "Preview not available.";

  const rollbackPreview = [
    `Rollback preview for job #${detail.id}`,
    `- Status would return to draft/validated state`,
    `- Steps would be marked skipped`,
    `- No SSH apply is executed in MVP`,
  ].join("\n");

  const validations = [
    `- Device count: ${detail.deviceIds.length}`,
    `- Template: ${template?.name ?? "N/A"}`,
    `- Job type: ${detail.type}`,
    `- Current status: ${detail.status}`,
  ].join("\n");

  const findings = detail.steps.length
    ? detail.steps.map((step: { stepName: string; status: string; errorMessage: string | null; }) => `- ${step.stepName}: ${step.status}${step.errorMessage ? ` (${step.errorMessage})` : ""}`).join("\n")
    : "- No findings recorded.";

  const targetDeviceLines = targetDevices.length
    ? targetDevices.map((device) => `- ${device.hostname} (${device.ipAddress})`).join("\n")
    : "- No target devices resolved.";

  const auditLines = auditTrail.length
    ? auditTrail.map((entry) => `- ${entry.createdAt.toISOString()} | ${entry.action} | ${entry.objectType}:${entry.objectId}`).join("\n")
    : "- No audit trail found.";

  return [
    `# Provisioning Report #${detail.id}`,
    "",
    `## Metadata`,
    `- Job name: ${detail.name}`,
    `- Service type: ${detail.type}`,
    `- Status: ${detail.status}`,
    `- Generated at: ${new Date().toISOString()}`,
    `- Generated by: system`,
    "",
    `## Customer / Target`,
    targetDeviceLines,
    "",
    `## Parameters`,
    parameters ? "```json\n" + JSON.stringify(parameters, null, 2) + "\n```" : "- No parameters provided.",
    "",
    `## Preview Config`,
    "```text\n" + previewConfig + "\n```",
    "",
    `## Rollback Preview`,
    "```text\n" + rollbackPreview + "\n```",
    "",
    `## Validations`,
    validations,
    "",
    `## Findings`,
    findings,
    "",
    `## Audit Trail`,
    auditLines,
    "",
    `## Steps`,
    detail.steps.length
      ? detail.steps.map((step) => `- ${step.deviceHostname ?? step.deviceId}: ${step.stepName} -> ${step.status}`).join("\n")
      : "- No steps recorded.",
  ].join("\n");
}

export async function createProvisioningReport(id: number, generatedBy: string | null = "system") {
  const contentMarkdown = await buildProvisioningJobReportMarkdown(id);
  if (!contentMarkdown) return null;
  const [report] = await db.insert(reportsTable).values({
    provisioningJobId: id,
    reportType: "markdown",
    contentMarkdown,
    generatedBy,
  }).returning();
  return report;
}
