import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import devicesRouter from "./devices.js";
import deviceGroupsRouter from "./device_groups.js";
import complianceRouter from "./compliance.js";
import templatesRouter from "./templates.js";
import provisioningRouter from "./provisioning.js";
import l2vpnRouter from "./l2vpn.js";
import provisioningPreviewRouter from "../modules/provisioning/provisioning-preview.routes.js";
import { provisioningTemplateRegistryRouter } from "../modules/provisioning/provisioning-template-registry.routes.js";
import { templateStudioRouter } from "../modules/provisioning/template-studio.routes.js";
import { serviceCatalogRouter } from "../modules/provisioning/service-catalog.routes.js";
import auditRouter from "./audit.js";
import reportsRouter from "./reports.js";
import integrationsRouter from "./integrations.js";
import schedulerRouter from "../modules/scheduler/scheduler.routes.js";
import netboxRouter from "../modules/netbox/netbox.routes.js";
import collectedConfigsRouter from "./collected_configs.js";
import snmpSnapshotsRouter from "./snmp_snapshots.js";
import netopsRouter from "../modules/netops/routes.js";
import discoveryRouter from "../modules/netops/device-discovery/discovery.routes.js";
import l2CircuitsRouter from "../modules/l2circuits/l2circuits.routes.js";
import operationalRouter from "../modules/operational/operational.routes.js";
import operationalBgpRouter from "../modules/operational-bgp/operational-bgp.routes.js";
import bgpDrilldownRouter from "../modules/bgp-drilldown/bgp-peer-drilldown.routes.js";
import bgpCleanupRouter from "../modules/bgp-drill-cleanup/bgp-drill-cleanup.routes.js";
import credentialVaultRouter from "../modules/credentials/credential-vault.routes.js";
import notificationsRouter from "../modules/notifications/notifications.routes.js";
import configHistoryRouter from "../modules/config-history/config-history.routes.js";
import bgpAnnouncementsRouter from "../modules/bgp-announcements/bgp-announcements.routes.js";
import { bgpRegistryRouter } from "../modules/bgp-registry/bgp-registry.routes.js";
import {
  connectorAgentRouter,
  connectorsManagementRouter,
} from "../modules/connectors/connectors.routes.js";
import resourceManagerRouter from "./resource-manager.js";
import topologyRouter from "./topology.js";
import impactRouter from "./impact.js";
import { authorizeRequest } from "../lib/auth.js";
import { requestContextMiddleware } from "../lib/request-context.js";

const router: IRouter = Router();

router.use(requestContextMiddleware);
router.use(healthRouter);
router.use(authRouter);
router.use(connectorAgentRouter);
router.use(authorizeRequest);
router.use(usersRouter);
router.use(devicesRouter);
router.use(deviceGroupsRouter);
router.use(complianceRouter);
router.use(templatesRouter);
router.use(provisioningRouter);
router.use("/l2vpn", l2vpnRouter);
router.use(provisioningPreviewRouter);
router.use(provisioningTemplateRegistryRouter);
router.use(templateStudioRouter);
router.use(serviceCatalogRouter);
router.use(auditRouter);
router.use(reportsRouter);
router.use(integrationsRouter);
router.use(netboxRouter);
router.use(schedulerRouter);
router.use(collectedConfigsRouter);
router.use(snmpSnapshotsRouter);
router.use(netopsRouter);
router.use(discoveryRouter);
router.use(l2CircuitsRouter);
router.use(operationalRouter);
router.use(operationalBgpRouter);
router.use(bgpDrilldownRouter);
router.use(bgpAnnouncementsRouter);
router.use(bgpRegistryRouter);
router.use(bgpCleanupRouter);
router.use(credentialVaultRouter);
router.use(notificationsRouter);
router.use(configHistoryRouter);
router.use(connectorsManagementRouter);
router.use(resourceManagerRouter);
router.use(topologyRouter);
router.use(impactRouter);

export default router;
