import { sanitizeEvidenceForExport } from "./compliance-report-sanitizer.js";
import type {
  ComplianceReportJson,
  ComplianceReportGroup,
  ComplianceReportFinding,
} from "./compliance-report-export.types.js";

export function exportComplianceReportMarkdown(report: ComplianceReportJson): string {
  const lines: string[] = [];

  // Header
  lines.push("# Compliance Report");
  lines.push("");

  // Summary section
  lines.push("## Summary");
  lines.push(
    `- **Job ID:** ${report.metadata.jobId}`,
    `- **Device:** ${report.metadata.deviceHostname}`,
    `- **Profile:** ${report.metadata.policyProfileName}`,
    `- **Status:** ${report.metadata.status}`,
    `- **Started at:** ${report.metadata.startedAt || "N/A"}`,
    `- **Completed at:** ${report.metadata.completedAt || "N/A"}`,
    `- **Generated at:** ${report.metadata.generatedAt}`,
    `- **Generated by:** ${report.metadata.generatedBy || "System"}`,
    ""
  );

  // Counters section
  lines.push("## Findings Summary");
  lines.push(
    `- **Total:** ${report.summary.totalFindings}`,
    `- **Pass:** ${report.summary.passCount}`,
    `- **Fail:** ${report.summary.failCount}`,
    ""
  );

  // By Severity
  if (Object.keys(report.summary.bySeverity).length > 0) {
    lines.push("### By Severity");
    for (const [severity, count] of Object.entries(report.summary.bySeverity)) {
      lines.push(`- **${severity}:** ${count}`);
    }
    lines.push("");
  }

  // By Status
  if (Object.keys(report.summary.byStatus).length > 0) {
    lines.push("### By Status");
    for (const [status, count] of Object.entries(report.summary.byStatus)) {
      lines.push(`- **${status}:** ${count}`);
    }
    lines.push("");
  }

  // By Category
  if (Object.keys(report.summary.byOperationalCategory).length > 0) {
    lines.push("### By Operational Category");
    for (const [category, count] of Object.entries(
      report.summary.byOperationalCategory
    )) {
      lines.push(`- **${category}:** ${count}`);
    }
    lines.push("");
  }

  // Top Finding Groups
  if (report.groups && report.groups.length > 0) {
    lines.push("## Top Finding Groups");
    lines.push("");
    lines.push(
      "| Severity | Category | Context | Rule | Count |"
    );
    lines.push("|----------|----------|---------|------|-------|");

    for (const group of report.groups.slice(0, 20)) {
      lines.push(
        `| ${group.severity} | ${group.operationalCategory} | ${group.context} | ${group.ruleName} | ${group.count} |`
      );
    }
    lines.push("");
  }

  // Findings table
  if (report.findings && report.findings.length > 0) {
    lines.push("## Findings");
    lines.push("");
    lines.push(
      "| Severity | Category | Context | Object | Message | Recommendation |"
    );
    lines.push(
      "|----------|----------|---------|--------|---------|-----------------|"
    );

    for (const finding of report.findings.slice(0, 100)) {
      const message = (finding.message || "").replace(/\|/g, "\\|").substring(0, 50);
      const recommendation = (finding.recommendation || "").replace(/\|/g, "\\|").substring(0, 50);
      lines.push(
        `| ${finding.severity} | ${finding.operationalCategory} | ${finding.context} | ${finding.objectName} | ${message} | ${recommendation} |`
      );
    }
    lines.push("");
  }

  // Evidence section (if included)
  if (report.sanitization.enabled) {
    lines.push("## Sanitization");
    lines.push(`- **Enabled:** Yes`);
    lines.push(`- **Rules Applied:** ${report.sanitization.rulesApplied.join(", ")}`);
    lines.push("");
  }

  // Footer
  lines.push("## Notes");
  lines.push("- Read-only report.");
  lines.push("- No configuration was applied.");
  lines.push("- Secrets and sensitive data have been sanitized.");
  lines.push("");
  lines.push("---");
  lines.push(`Generated: ${new Date().toISOString()}`);

  return lines.join("\n");
}
